export const CLICK_HAMBURGER = "CLICK_HAMBURGER";

export const CLOSE_HEADER_NOTIFICATION = "CLOSE_HEADER_NOTIFICATION";

export const TOGGLE_REVIEW = "TOGGLE_REVIEW";

export const SEND_EMAIL = "SEND_EMAIL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SET_CURRENTLY_SEARCHING = "SET_CURRENTLY_SEARCHING";

export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";

export const GET_POST_DATA = "GET_POST_DATA";
export const GET_COMMENT_DATA = "GET_COMMENT_DATA";

export const CLEAR_RESULTS = "CLEAR_RESULTS";

export const TOGGLE_SORT = "TOGGLE_SORT";
