export const CLICK_HAMBURGER = 'CLICK_HAMBURGER';

export const CLOSE_HEADER_NOTIFICATION = 'CLOSE_HEADER_NOTIFICATION';

export const ACTIVATE_REVIEW = 'ACTIVATE_REVIEW';
export const DEACTIVATE_REVIEW = 'DEACTIVATE_REVIEW';

export const SEND_EMAIL = 'SEND_EMAIL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
